apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atlas-files-encrypted
  namespace: atlas
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi