apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atlas-files
  namespace: atlas
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: aws-efs
  resources:
    requests:
      storage: 1Gi