apiVersion: v1
kind: Secret
metadata:
  name: atlas-secrets
  namespace: atlas
type: Opaque
stringData:
  JWTSecretKey: "JWTSecretKeyFromSomeWhere6789012"
  SQLConn: "Server=tcp:yourdatabase.database.windows.net,1433;Initial Catalog=ATLAS;Persist Security Info=False;User ID=youruserID;Password=yourPassword;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
  EncryptionKey: "YourEncryptionKeyFromSomeWhere12"