---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-regscale
  namespace: regscale
type: Opaque
stringData:
  JWTSecretKey: <YOUR JWT KEY 32 CHARS>
  SQLConn: "Server=tcp:<YOUR DB CONNECTION STRING>,1433;Initial Catalog=ATLAS;Persist Security Info=False;User ID=<YOUR DB USER>;Password=<YOUR DB PASSWORD>=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;"
  EncryptionKey: <YOUR ENCRYPTION KEY 32 CHARS>