---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: regscale-files
  namespace: regscale
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 10Gi #adjust this to your desired size