---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: atlas-efs-nfs-pv
spec:
  capacity:
    storage: 10Gi #adjust this to your desired size
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - timeo=600
    - retrans=2
  nfs:
    path: /
    server: <FileSystemId>.efs.<Region>.amazonaws.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atlas-files
  namespace: atlas
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi #adjust this to your desired size